name: pypsa-za
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - six
  - snakemake
  - numpy
  - pyomo
  - scipy
  - pandas>=0.22.0
  - xlrd
  - matplotlib
  - seaborn
  - networkx>=1.10
  - pyomo
  - netcdf4
  - xarray
  - cartopy #==0.21.0 #agatha

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  - ipython==8.6.0 #agatha

  # GIS dependencies have to come all from conda-forge
  - conda-forge::libgdal
  - conda-forge::fiona
  - conda-forge::pyproj
  - conda-forge::pyshp
  - conda-forge::geopandas
  - conda-forge::rasterstats
  - conda-forge::rasterio
  - conda-forge::shapely<=1.8.5

  - pip:
    - pypsa #==0.21.3 #agatha
    - vresutils>=0.2.4
    - countrycode
    - atlite #agatha
    - rioxarray #agatha
    - tsam #agatha
    - openpyxl # lisa
    - powerplantmatching # lisa
    - fiona #==1.8.22 #agatha
    #- gdal==3.5.3 #agatha
    - dask==2022.10.2 #agatha

